RobotConfig:
  _target_: lerobot.robots.ufactory_robot.UFRobotConfig
  id: "lab"
  robot_ip: "192.168.1.85"
  robot_dof: 7
  control_space: "joint"
  gripper_control: True

DatasetRecordConfig:
  _target_: lerobot.scripts.lerobot_record.DatasetRecordConfig
  # root of local repo: /home/<user_name>/.cache/huggingface/lerobot (default)
  # repo_id: "ufactory/xarm7_act_mock_20260126"
  repo_id: "ufactory/xarm7_record_datas"
  single_task: "Pick up the Lego block and drop into the box on the right."
  fps: 30
  episode_time_s: 60  # max duration for one episode
  reset_time_s: 20  # time for resetting env between episodes
  push_to_hub: False

# make sure to edit with your correct configurations!
TeleoperatorConfig:
  _target_: lerobot.teleoperators.ufactory_mock.UFactoryMockConfig
  robot_ip: "192.168.1.85"
  control_space: "joint"    # joint/cartesian
  fps: 30  # Hz
  mock_type: 1
  mock_x_range: [180, 600]    # mm
  mock_y_range: [-280, 50]    # mm
  mock_z_range: [180, 180]    # mm
  mock_roll_range: [180, 180] # °
  mock_pitch_range: [0, 0]    # °
  mock_yaw_range: [-90, 90]   # °
  mock_tcp_speed: 200           # mm/s
  hover_offset: 200             # mm
  grasp_tcp_speed: 150          # mm/s
  place_tcp_speed: 100          # mm/s
  place_tcp_pose: [383, 253, 320, 180, 0, 0]  # x,y,z in mm; roll,pitch,yaw in °
  initial_tcp_pose: [450, 0, 520, 180, 0, 0, 0]  # x,y,z in mm; roll,pitch,yaw in °
  gripper_type: 1  # 0: no gripper, 1: xArm Gripper, 2: xArm Gripper G2
  gripper_freq: 50  # Hz
  gripper_open: 800
  gripper_close: 0
